### ISSUE TITLE
android compile not working

### ISSUE THREAD

**Issue by FalconEagleTest** [ivk1800/prebuild#3]
hi,
i fixed the issue you can see the solution in my fork:
https://github.com/FalconEagleTest/td-json-client-prebuilt/edit/master/.github/workflows/build-tdlib.yml

**Comment by wudb** [comment]
> hi, i fixed the issue you can see the solution in my fork: https://github.com/FalconEagleTest/td-json-client-prebuilt/edit/master/.github/workflows/build-tdlib.yml

E/flutter ( 6270): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol '_td_json_client_create': undefined symbol: _td_json_client_create
E/flutter ( 6270): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
E/flutter ( 6270): #1      JsonBindings._clientCreate (package:tdlib/src/client/platform/io/json_bindings.dart:31)
E/flutter ( 6270): #2      JsonBindings.createClient (package:tdlib/src/client/platform/io/json_bindings.dart)
E/flutter ( 6270): #3      PlatformImpl.initialize (package:tdlib/src/client/platform/io/io_platform.dart:26)
E/flutter ( 6270): #4      ClientImpl.initialize (package:tdlib/src/client/client_impl.dart:70)
E/flutter ( 6270): #5      TGClient.setup (package:telegram_ai/tgclient.dart:30)
E/flutter ( 6270): #6      main (package:telegram_ai/main.dart:10)
E/flutter ( 6270): #7      _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
E/flutter ( 6270): #8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
E/flutter ( 6270): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
E/flutter ( 6270): 

Hello,
After I used the android so file you packaged, I reported this error. The packaged so of this repo does not work under release.
